version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
      - cd frontend && npm install && cd ..
  build:
    commands:
      - echo Deploying GorgonZola on `date`
      - cd cdk && npx cdk bootstrap aws://265927627858/us-east-1 && cd ..
      - npm run deploy
